name: Promote to Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  promote-release:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    name: Promote main to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create empty CHANGELOG.md
        run: touch CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          committer: 'TempWynntilsBot <admin@tempwynntils.com>'
          commit-message: "chore: Create changelog"
          title: "chore: Create changelog for release"
          body: "Edit the changelog"
          branch: promote-to-release
          base: release
          add-paths: |
            CHANGELOG.md
