
name: Promote to Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  promote-release:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    name: Promote main to release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout main branch
          uses: actions/checkout@v4
          with:
            ref: main
            fetch-depth: 0

        - name: Set up Git
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: Fetch release branch
          run: git fetch origin release:release

        - name: Create new branch from main
          run: |
            git checkout -b release-update

        - name: Reset Changelog
          run: |
            echo "" > CHANGELOG.md
            git add CHANGELOG.md
            git commit -m "chore: Reset Changelog"

        - name: Create Pull Request into release
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base: release
            branch: release-update
            title: "chore: Create changelog for release"
            commit-message: "chore: Create changelog for release"
            delete-branch: true
