name: Promote to Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  promote-release:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    name: Promote main to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Merge main into release
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          source: 'main'
          target: 'release'

      - name: Reset CHANGELOG.md
        run: |
          git config --global user.name "WynntilsBot"
          git config --global user.email "admin@wynntils.com"
          git fetch origin release
          git checkout release
          echo "" > CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: Reset changelog"
          git push origin release
