
name: Promote to Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  promote-release:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    name: Promote main to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reset changelog
        run: |
          touch CHANGELOG.md
          echo -n "" > CHANGELOG.md
          git add CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          committer: 'TempWynntilsBot <admin@tempwynntils.com>'
          branch: promote-to-release
          base: release
          title: "chore: Create changelog for release"
          commit-message: "chore: Create changelog"
          delete-branch: true
