name: Publish Release

on:
  push:
    branches:
      - release
    paths:
      - 'CHANGELOG.md'

jobs:
  set-version:
    name: Set Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      skipped: ${{ steps.version.outputs.skipped }}
      changelog: ${{ steps.version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: |
          npm install conventional-changelog-conventionalcommits@7.0.2
          npm install conventional-recommended-bump@9.0.0

      - name: Set up version.json
        run: echo "{"version":$(git describe --tags --abbrev=0)}" > version.json

      - name: Generate version tag
        id: version
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          git-user-name: 'WynntilsBot'
          git-user-email: 'admin@wynntils.com'
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          version-file: ./version.json
          skip-version-file: true
          skip-git-pull: true
          pre-release: false
          release-count: 0
          output-file: false

      - name: Upload version information
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.gradle

  build:
    name: Build
    needs: [set-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle data
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle--${{ hashFiles('**/settings.gradle', '**/gradle.properties') }}

      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew buildDependents -x spotlessCheck -x test

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-neoforge+MC-*.jar
          if-no-files-found: error
          overwrite: true

  release-github:
    name: Release to GitHub
    if: ${{ needs.set-version.outputs.skipped != 'true' }}
    runs-on: ubuntu-latest
    needs: [build, set-version]
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}
          ref: release

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Get previous and current versions
        id: versions
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "previous=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "current=${{ needs.set-version.outputs.tag }}" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "long=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Build GitHub release body
        id: build_release_body
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "## [${{ steps.versions.outputs.current }}](https://github.com/Wynntils/Wynntils/compare/${{ steps.versions.outputs.previous }}...${{ steps.versions.outputs.current }}) (${{ steps.date.outputs.today }})" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          tag_name: ${{ needs.set-version.outputs.tag }}
          body: ${{ steps.build_release_body.outputs.content }}
          draft: false
          prerelease: false
          files: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-neoforge+MC-*.jar

      - name: Generate artifact links
        id: artifact_links
        run: |
          TAG=${{ needs.set-version.outputs.tag }}
          BASE_URL="https://github.com/Wynntils/Wynntils/releases/download/$TAG"

          FILES=$(find . -path "*/build/libs/*-fabric+MC-*.jar" -or -path "*/build/libs/*-neoforge+MC-*.jar")

          echo "links=" >> $GITHUB_OUTPUT
          for f in $FILES; do
            NAME=$(basename "$f")
            URL="$BASE_URL/${NAME//+/%2B}"
            echo "- [$NAME]($URL)" >> $GITHUB_OUTPUT
          done

      - name: Post release on Discord
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_BUILDS_WEBHOOK_URL }}
          embed-color: "9498256"
          embed-title: Wynntils ${{ needs.set-version.outputs.tag }}
          embed-url: ${{ steps.release.outputs.url }}
          embed-description: |
            [Click here to see release notes](https://discord.com/channels/150059149762027520/493174334475468800)

            ${{ steps.artifact_links.outputs.links }}
          embed-timestamp: ${{ steps.date.outputs.long }}
