  release-github:
    name: Release to GitHub
    if: ${{ needs.changelog.outputs.skipped != 'true' }}
    runs-on: ubuntu-latest
    needs: [build, changelog]
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}
          ref: release

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Read entire CHANGELOG.md
        id: read_changelog
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ steps.read_changelog.outputs.content }}
          draft: false
          prerelease: false
          files: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-neoforge+MC-*.jar
