name: Release Test
on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.1-test
          name: Test Release
          body: This is a test
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
